//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace University.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentSituation
    {
        public System.Guid StudentId { get; set; }
        public System.Guid SchoolSubjectId { get; set; }
        public string SchoolSubjectName { get; set; }
        public decimal ActivityGrade { get; set; }
        public decimal ExamGrade { get; set; }
        public decimal FinalGrade { get; set; }
    }
}
